name: "Release"
on: 
   push:
       tags:       
         - '*'

jobs:
  call-build-release:
    uses: reusable-release.yml
    with:
      filename: "CI-build-test-groovy-archive"
      filelocation: "./CI-build-test.groovy"   
