name: "Release"
on: 
   push:
       tags:       
         - '*'

jobs:
  call-workflow-passing-data:
    uses: CommonWealthRobotics/Bowler-Script-Release-CI/.github/workflows/reusable-release.yml@main
    with:
      filename: "CI-build-test"
      filelocation: "./CI-build-test.groovy"   
