name: "Release"
on: 
   push:
       tags:       
         - '*'

jobs:
  call-build-release:
    uses: CommonWealthRobotics/Bowler-Script-Release-CI/.github/workflows/reusable-release.yml@feature/returnpath
    with:
      filename: "CI-build-test-groovy-archive"
      filelocation: "./CI-build-test.groovy"   
