name: "Release"
on: 
   push:
       tags:       
         - '*'

jobs:
  call-release:
    uses: CommonWealthRobotics/Bowler-Script-Release-CI/.github/workflows/reusable-release.yml@feature/returnpath
    needs: call-build
    with:
      filename: "CI-build-test-groovy-archive"
      filelocation: "./CI-build-test.groovy"   
  use-url-job:
    runs-on: ubuntu-latest
    needs: call-release
    steps:
      - run: echo "URL is:"${{ needs.call-release.outputs.outputURL }} 