name: Build and Release Bowler Script

on:
  workflow_call:
    inputs:
      filename:
        required: true
        type: string
      filelocation:
        required: true
        type: string
    outputs:
            outputURL:
              description: "The URL of upload" 
              value: ${{ jobs.reusable_workflow_job.outputs.output1 }}
   
jobs:
   reusable_workflow_job:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.storeURLStep.outputs.outputURL }}
    steps:
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        path: 'manufacturing'
        filename: '${{ inputs.filename }}-${{ steps.get_version.outputs.VERSION }}.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Show Build
      run: ls -al .
         
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
            draft: false
            prerelease: false
            release_name: ${{ steps.get_version.outputs.VERSION }}
            tag_name: ${{ github.ref }}
      env:
            GITHUB_TOKEN: ${{ github.token }}
            
    - name: Upload Zip of Build Artifacts
      uses: actions/upload-release-asset@v1
      env:
            GITHUB_TOKEN: ${{ github.token }}
      with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ${{ inputs.filename }}-${{ steps.get_version.outputs.VERSION }}.zip
            asset_name: ${{ inputs.filename }}-${{ steps.get_version.outputs.VERSION }}.zip
            asset_content_type: application/binary
    - name: Store URL
      id: storeURLStep
      run: echo "::set-output name=outputURL::https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/releases/download/${{ steps.get_version.outputs.VERSION }}/${{ inputs.filename }}-${{ steps.get_version.outputs.VERSION }}.zip"   
   
