name: Reusable workflow example

on:
  workflow_call:
    inputs:
      filename:
        required: true
        type: string
      filelocation:
        required: true
        type: string

jobs:
   reusable_workflow_job:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
         submodules: recursive 
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}   
      
    - name: start xvfb
      run:
        Xvfb :99 &

    - name: initialize the X11 DISPLAY variable
      run:
        export DISPLAY=:99

    - name: After checkout, list directory contnts
      run: pwd; ls -la        

    - name: Pull a JavaFX JDK
      run: wget http://static.azul.com/zulu/bin/zulu8.33.0.1-ca-fx-jdk8.0.192-linux_x64.tar.gz

    - name: After JDK download, list directory contnts
      run: pwd; ls -la

    - name: Set Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        jdkFile: ./zulu8.33.0.1-ca-fx-jdk8.0.192-linux_x64.tar.gz

    - name: Download Bowler kernel into CI
      run: wget https://github.com/CommonWealthRobotics/bowler-script-kernel/releases/latest/download/bowler-kernel.jar
      
    - name: Compile three-eighths spacers
      run: java -jar bowler-kernel.jar -f ${{ inputs.filelocation }}
      
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        path: 'manufacturing'
        filename: '${{ inputs.filename }}.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'

    - name: three-eighths spacer STL
      uses: actions/upload-release-asset@v1
      env:
            GITHUB_TOKEN: ${{ github.token }}
      with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ${{ inputs.filename }}.zip
            asset_name: ${{ inputs.filename }}.zip
            asset_content_type: application/binary
