name: Build and Release Bowler Script

on:
  workflow_call:
    inputs:
      filename:
        required: true
        type: string
      filelocation:
        required: true
        type: string
    outputs:
            outputURL:
              description: "The URL of upload" 
              value: ${{ jobs.reusable_workflow_job.outputs.output1 }}
   
jobs:
   reusable_workflow_job:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.storeURLStep.outputs.outputURL }}
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
         submodules: recursive 
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}   
    - name: Print Home
      run: echo $HOME 
    - name: Print Workspace
      run: echo $PWD       
    - name: Link source Into Workspace 1
      run: mkdir -p $HOME/Documents/bowler-workspace/gitcache/github.com/${{ github.repository_owner }}/
    - name: Link source Into Workspace 2
      run: ln -s $PWD $HOME/Documents/bowler-workspace/gitcache/github.com/${{ github.repository_owner }}/
    - name: Link source Into Workspace 3
      run: ls -al $HOME/Documents/bowler-workspace/gitcache/github.com/
    - name: Link source Into Workspace 4
      run: ls -al $HOME/Documents/bowler-workspace/gitcache/github.com/${{ github.repository_owner }}/ 
    - name: Link source Into Workspace 5
      run: ls -al $HOME/Documents/bowler-workspace/gitcache/github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/
      
    - name: Install libraries
      run: |
          sudo apt update
          sudo apt install libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev libgtk2.0-0
    - name: start xvfb
      run:
        Xvfb :0 &

    - name: initialize the X11 DISPLAY variable
      run:
        export DISPLAY=:0

    - name: After checkout, list directory contnts
      run: pwd; ls -la        

    - name: Pull a JavaFX JDK
      run: wget http://static.azul.com/zulu/bin/zulu8.33.0.1-ca-fx-jdk8.0.192-linux_x64.tar.gz

    - name: After JDK download, list directory contnts
      run: pwd; ls -la

    - name: Set Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        jdkFile: ./zulu8.33.0.1-ca-fx-jdk8.0.192-linux_x64.tar.gz

    - name: Download Bowler kernel into CI
      run: wget https://github.com/CommonWealthRobotics/bowler-script-kernel/releases/latest/download/bowler-kernel.jar
      
    - name: Compile Script
      run: xvfb-run -s '-screen 0 1024x768x24' java -Dprism.verbose=true -Dprism.forceGPU=true -d64 -Xmx6500M -jar bowler-kernel.jar -f "${{ inputs.filelocation }}"
    - name: Setup filename without spaces      
      run: |
       FILENAME="${{ inputs.filename }}"
       FILENAME=${FILENAME// /-}  # Replace all spaces with hyphens
       echo "CLEAN_FILENAME=$FILENAME" >> $GITHUB_ENV

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        path: 'manufacturing'
        filename: "${{ env.CLEAN_FILENAME }}-${{ steps.get_version.outputs.VERSION }}.zip"
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Show Build
      run: ls -al .
         
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
            draft: false
            prerelease: false
            release_name: ${{ steps.get_version.outputs.VERSION }}
            tag_name: ${{ github.ref }}
      env:
            GITHUB_TOKEN: ${{ github.token }}
            
    - name: Upload Zip of Build Artifacts
      uses: actions/upload-release-asset@v1
      env:
            GITHUB_TOKEN: ${{ github.token }}
      with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: "${{ env.CLEAN_FILENAME }}-${{ steps.get_version.outputs.VERSION }}.zip"
            asset_name: "${{ env.CLEAN_FILENAME }}-${{ steps.get_version.outputs.VERSION }}.zip"
            asset_content_type: application/binary
    - name: Store URL
      id: storeURLStep
      run: echo "::set-output name=outputURL::https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/releases/download/${{ steps.get_version.outputs.VERSION }}/${{ inputs.filename }}-${{ steps.get_version.outputs.VERSION }}.zip"   
   
